# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/ticketdatabase # using the container here
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret-key: "your_super_secure_and_long_secret_key"
  token-validity: 18000 # in seconds (5 hours)

logging:
  level:
    org:
      springframework:
        security: DEBUG
    edu:
      miu:
        ticket_system:
          util:
            JwtUtil: DEBUG

